name = "ai-n"

# The following fields are optional but recommended
compatibility_date = "2023-01-01"

# Specify the directory where your build outputs your static files
pages_build_output_dir = "build/client"

[env.production]
name = "ai-n-production"

[env.preview]
name = "ai-n-preview"
